[project]
name = "foo"
version = "0.1.0"
authors = [
    { name = "Lingbo Peng", email = "lb.peng@aftership.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"
